---
name: Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  role-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@main
    name: OIDC Role Module
    with:
      working-directory: modules/role

  remote-state-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@main
    name: Remote State Module
    with:
      working-directory: modules/remote-state

  provider-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@main
    name: Provider Module
    with:
      working-directory: modules/provider
